GET http://localhost:3001/api/posts
Content-Type: application/json

###

POST http://localhost:3001/api/posts
Content-Type: application/json

{
    "username": "Yoshi",
    "topic": "Did it even 1111111work lol",
    "info": "true",
    "image": "./images/No-Image.png"
}

### 

DELETE http://localhost:3001/api/posts/6418f7714bdea7998ddefef2
Content-Type: application/json

### 

DELETE http://localhost:3001/api/posts
Content-Type: application/json